- name: setup todoapp project
  hosts: all
  become: yes
  roles:
    - role: frontend1
      tags: frontend1
      when: COMPONENT == "frontend1"

    - role: login1
      tags: login1
      when: COMPONENT == "login1"

    - role: users
      tags: users
      when: COMPONENT == "users"

    - role: redis
      tags: redis
      when: COMPONENT == "redis"

    - role: todo1
      tags: todo1
      when: COMPONENT == "todo1"
