- name: setup todoapp project
  hosts: all
  become: yes
  roles:
    - role: frontend
      tags: frontend
      when: COMPONENT == "frontend"

    - role: login
      tags: login
      when: COMPONENT == "login"

    - role: users
      tags: users
      when: COMPONENT == "users"

    - role: redis
      tags: redis
      when: COMPONENT == "redis"

    - role: todo
      tags: todo
      when: COMPONENT == "todo"
