- name: Install Golang
  apt:
    name: golang
    state: present
    update_cache: yes

- name: Download login1 from nexus
  get_url:
    url: http://172.31.8.88:8081/repository/login1/login1-{{APP_VERSION}}.zip
    dest: /tmp/login1.zip
    username: admin
    password: admin123

- name: Clean the old artifacts
  file:
    path: /root/login1
    state: absent

- name: Create path of artifacts
  file:
    path: /root/login1
    state: directory

- name: Extract the login1 content
  unarchive:
    src: /tmp/login1.zip
    dest: /root/login1
    remote_src: yes
- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true

- set_fact:
    go_path: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go', true) }}"
  when: not result|failed

- name: go get repos
  shell: go get github.com/openzipkin/zipkin-go && go get github.com/openzipkin/zipkin-go/middleware/http && go get github.com/openzipkin/zipkin-go/reporter/http && go get github.com/labstack/echo && go get github.com/labstack/echo/middleware && go get github.com/labstack/gommon/log
  environment:
    GOPATH: "{{ go_path }}"
  register: gogs
  when: not result|failed

- debug: var=gogs

- name: Copy login1 service file
  copy:
    src: login1.service
    dest: /etc/systemd/system/login1.service

- name: start login1 service
  systemd:
    name: login1
    daemon-reload: yes
    state: started
    enabled: yes

