- name: Install Golang
  apt:
    name: golang
    state: present
    update_cache: yes

- name: Download Artifacts from Nexus
  include_role:
    name: common
    tasks_from: download-nexus-artifacts

- name: Configure Go get Repos
  shell: |
    go get github.com/openzipkin/zipkin-go
    go get github.com/openzipkin/zipkin-go/middleware/http
    go get github.com/openzipkin/zipkin-go/reporter/http
    go get github.com/labstack/echo
    go get github.com/labstack/echo/middleware
    go get github.com/labstack/gommon/log
  environment:
    GOROOT: /usr/lib/go
    GOPATH: /root/login1

- name: Setup SystemD Service
  include_role:
    name: common
    tasks_from: systemd

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter

- name: Install Filebeat Monitoring
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    IS_STRUCTURED: true
    LOG_FILES:
      - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" }


