- name: Install npm
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Download Artifacts from Nexus
  include_role:
    name: common
    tasks_from: download-nexus-artifacts


- name: Setup SystemD Service
  include_role:
    name: common
    tasks_from: systemd

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter



