- name: Install npm
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Download frontend1 from nexus
  get_url:
    url: http://172.31.8.88:8081/repository/frontend1/frontend1.zip
    dest: /tmp/frontend1.zip
    username: admin
    password: admin123

- name: Clean the old artifacts
  file:
    path: /home/ubuntu/frontend1
    state: absent

- name: Create path of artifacts
  file:
    path: /home/ubuntu/frontend1
    state: directory

- name: Extract the frontend1 content
  unarchive:
    src: /tmp/frontend1.zip
    dest: /home/ubuntu/frontend1
    remote_src: yes

- name: Copy frontend1 service file
  copy:
    src: frontend1.service
    dest: /etc/systemd/system/frontend1.service

- name: start frontend1 service
  systemd:
    name: frontend1
    daemon-reload: yes
    state: started
    enabled: yes