- name: Install npm
  apt:
    name: npm
    state: prsent
    update_cache: yes

- name: Download frontend from nexus
  get_url:
    url: "file:///tmp/aile.txt"
    dest: /tmp/frontend.zip
    username: admin
    password: admin123

- name: Clean the old artifacts
  file:
    path: /home/ubuntu/frontend
    state: absent

- name: Create path of artifacts
  file:
    path: /home/ubuntu/frontend
    state: directory

- name: Extract the frontend content
  unarchive:
    src: /tmp/frontend.zip
    dest: /home/ubuntu/frontend
    remote_src: yes
