- name: Install npm
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Download Artifacts from Nexus
  include_tasks: download-nexus-artifacts.yml


- name: Install nodemon
  shell: npm i nodemon && npm link nodemon

- name: Setup SystemD Service
  include_tasks: systemd.yml