- name: Install a list of packages
  apt:
    pkg:
      - openjdk-8-jre-headless
      - openjdk-8-jdk-headless
      - maven
    update_cache: yes

- name: Download Artifacts from Nexus
  include_tasks: download-nexus-artifacts.yml

- name: Setup SystemD Service
  include_tasks: systemd.yml


