- hosts: all
  become: yes
  tasks:
    - name: Unarchive a file that needs to be downloaded
      unarchive:
        src: https://golang.org/dl/go1.15.5.linux-amd64.tar.gz
        dest: /usr/local
        remote_src: yes